import type { Readable } from 'node:stream';

export interface ObjectHead {
  size: number;
  contentType: string | null;
  etag: string | null;
}

export interface UploadTarget {
  method: 'POST' | 'PUT';
  url: string;
  /** Form fields for POST uploads (must precede the file field). */
  fields: Record<string, string>;
  /** Headers the client must send for PUT uploads. */
  headers: Record<string, string>;
  expiresAt: string;
}

export interface SignedUrlOptions {
  expiresInSeconds: number;
  /** Force download with this file name. */
  downloadName?: string;
  contentType?: string;
}

/**
 * Object storage abstraction. Keys are generated by services (never user file names) and buckets
 * are private: clients only ever receive time-limited signed URLs.
 */
export interface ObjectStorage {
  readonly driver: 's3' | 'local';
  putObject(key: string, body: Buffer | Readable, options: { contentType: string; contentLength?: number }): Promise<void>;
  getObject(key: string): Promise<{ body: Readable; contentType: string | null; size: number }>;
  getBytes(key: string, range?: { start: number; end: number }): Promise<Buffer>;
  headObject(key: string): Promise<ObjectHead | null>;
  deleteObject(key: string): Promise<void>;
  deletePrefix(prefix: string): Promise<number>;
  copyObject(sourceKey: string, targetKey: string): Promise<void>;
  createUploadTarget(key: string, options: { contentType: string; maxBytes: number; expiresInSeconds: number }): Promise<UploadTarget>;
  signedGetUrl(key: string, options: SignedUrlOptions): Promise<string>;
  ping(): Promise<void>;
}
